site_name: AVWX Support
site_url: https://support.avwx.rest
site_description: Support site for the AVWX REST API
site_author: Michael duPont

repo_url: https://github.com/avwx-rest/api-support-site
edit_url: ""

theme: lumen

nav:
  - API:
    - API Usage: api.md
    - Token: token.md
    - HTTP Codes: http_codes.md
  - Account:
    - Feature Tiers: tiers.md
    - Payment Processing: payment.md

copyright: Copyright &copy; 2021 duPont Technologies LLC

plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
