site_name: AVWX Support
site_url: https://support.avwx.rest
site_description: Support site for the AVWX REST API
site_author: Michael duPont

repo_url: https://github.com/avwx-rest/api-support-site

theme:
  name: material
  logo: assets/images/avwx-icon-32-white.png
  favicon: assets/images/favicon.ico

extra:
  homepage: https://avwx.rest

extra_css:
  - assets/stylesheets/extra.css

nav:
  - API:
    - API Usage: api.md
    - Token: token.md
    - HTTP Codes: http_codes.md
    - Data Sources: data.md
  - Account:
    - Feature Tiers: tiers.md
    - Payment Processing: payment.md
  - Legal:
    - Terms of Service: terms.md
    - Privacy Policy: privacy.md

copyright: Copyright &copy; 2023 duPont Technologies LLC

plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
