site_name: AVWX Support
site_author: Michael duPont
repo_url: https://github.com/avwx-rest/api-support-site

nav:
  - API:
    - API Usage: api.md
    - Token: token.md
    - HTTP Codes: http_codes.md
  - Account:
    # - Account Management: account.md
    - Feature Tiers: tiers.md
    - Payment Processing: payment.md

plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

theme: lumen

copyright: Copyright &copy; 2021 duPont Technologies LLC